# Generated by Django 4.1.5 on 2023-05-25 19:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input category name', max_length=50)),
                ('description', models.CharField(help_text='Input Description', max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primarycolor_page', colorfield.fields.ColorField(default='#00234D', help_text='Input Primary color of the page.', image_field=None, max_length=18, samples=None, verbose_name='Primary color of the page')),
                ('secundarycolor_page', colorfield.fields.ColorField(default='#F76B6A', help_text='Input Secundary color of the page.', image_field=None, max_length=18, samples=None, verbose_name='Secundary color of the page')),
                ('logo', models.ImageField(help_text='Input Logo.', upload_to='logos/', verbose_name='Logo')),
                ('url', models.CharField(default='', help_text='Input URL', max_length=500, verbose_name='Url para la api de usuarios de GainUp')),
                ('color_footer', colorfield.fields.ColorField(default='#00234D', help_text='Input color of the footer.', image_field=None, max_length=18, samples=None, verbose_name='Color of the footer')),
                
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(default='', help_text='Input name image', max_length=100, verbose_name='Product name image')),
                ('image', models.ImageField(help_text='Input Product image', upload_to='imgproduct/', verbose_name='Product image')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input category name', max_length=50)),
                ('address', models.CharField(blank=True, help_text='Input Address ', max_length=50, verbose_name='Address')),
                ('phone_number', models.CharField(default='', help_text='Input Phone number', max_length=20, verbose_name='Phone number')),
                ('email', models.EmailField(help_text='Input email address.', max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', help_text='Input First name', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(default='', help_text='Input Last name', max_length=50, verbose_name='Last name')),
                ('phone_number', models.CharField(default='', help_text='Input Phone number', max_length=20, verbose_name='Phone number')),
                ('address', models.CharField(help_text='Input Address ', max_length=50, verbose_name='Address')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting_for_approval', 'Waiting For Approval')], default='waiting_for_approval', help_text='Input Status', max_length=20, verbose_name='Status')),
                ('articles', models.TextField(default='', help_text='Input Articles', verbose_name='Articles')),
                ('date_of_purchase', models.DateField(auto_now_add=True, help_text='The date on which the transaction was made.', verbose_name='Date of purchase')),
                ('email', models.EmailField(help_text='Input email address.', max_length=254, verbose_name='email address')),
                ('total_amount', models.DecimalField(decimal_places=6, help_text='The total amount of the purchase.', max_digits=16, verbose_name='Total amount of the purchase')),
                ('type_pay', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', help_text='Input Type Pay', max_length=25, verbose_name='Type Pay')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_product', models.CharField(help_text='Input Product reference', max_length=100, verbose_name='Product reference')),
                ('name_product', models.CharField(help_text='Input Product name', max_length=100, verbose_name='Product name')),
                ('description_product', models.TextField(help_text='Input Product description', verbose_name='Product description')),
                ('buy_price', models.DecimalField(decimal_places=6, default=0, help_text='Input Price of the product', max_digits=16, verbose_name='Price of the product')),
                ('price_product', models.DecimalField(decimal_places=6, default=0, help_text='Input Price of the product', max_digits=16, verbose_name='Price of the product')),
                ('price_false', models.DecimalField(decimal_places=6, default=0, help_text='Input Price false of the product', max_digits=16, verbose_name='Price false of the product')),
                ('quantity', models.IntegerField(default=0, help_text='Input Price false of the product', verbose_name='Price false of the product')),
                ('categories', models.ManyToManyField(help_text='Input Product category', related_name='productCategory', to='almacen.category', verbose_name='Product category')),
                ('images', models.ManyToManyField(help_text='Input Product image', related_name='productimg', to='almacen.productimage', verbose_name='Product image')),
                ('provider', models.ManyToManyField(help_text='Input Product Provider', related_name='productProvider', to='almacen.provider', verbose_name='Product Provider')),
            ],
            options={
                'verbose_name': 'Product Information',
                'verbose_name_plural': 'Products Information',
            },
        ),
    ]
