# Generated by Django 4.1.5 on 2023-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='buy_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Input Buy Price of the product', max_digits=16, verbose_name='Buy Price of the product'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='name_product',
            field=models.CharField(help_text='Input Product name', max_length=200, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Input Quantity of the product', verbose_name='Quantity of the product'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='reference_product',
            field=models.CharField(help_text='Input Product reference', max_length=200, verbose_name='Product reference'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, help_text='Input Address ', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='address',
            field=models.CharField(help_text='Input Address ', max_length=400, verbose_name='Address'),
        ),
    ]
